name: Publish wfaas

permissions:
  contents: read

on:
  push:
    branches: [main]
    paths: [workflow/Cargo.toml]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/publish-crate
        with:
          crate: wfaas
          path: workflow
          token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
